### ISSUE TITLE
i get error Iteration and DataFrame creation

### ISSUE THREAD

**Issue by ajransaputra** [PetengDedet/Ubuntu-Authlog-Visualization#1]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-073c1ee1d0d8> in <module>
      3 
      4 for line in d:
----> 5     obj = get_error_login(line)
      6     if obj:
      7         attempts.append(obj.dict_from_class())

<ipython-input-15-c1d683f33d0a> in get_error_login(line)
     23     if match:
     24         g = match.groups()
---> 25         obj = LoginAttempt(g[0], g[1], g[2])
     26         return obj
     27     else:

<ipython-input-14-9458dc486535> in __init__(self, timestamp, username, ip_address)
     15         self.username = username
     16         self.ip_address = ip_address
---> 17         self.lookup_ip(ip_address)
     18         self.dayname = datetime.datetime.strptime(timestamp, "%b %d %H:%M:%S").strftime("%a")
     19         self.hour = datetime.datetime.strptime(timestamp, "%b %d %H:%M:%S").strftime("%H")

<ipython-input-14-9458dc486535> in lookup_ip(self, ip)
     28 
     29     def lookup_ip(self, ip):
---> 30         match = geolite2.lookup(ip)
     31         if match:
     32             self.country_code = match.country

C:\ProgramData\Anaconda3\lib\site-packages\geoip.py in lookup(self, ip_addr)
    362 
    363     def lookup(self, ip_addr):
--> 364         return self._get_actual_db().lookup(ip_addr)
    365 
    366     def __repr__(self):

C:\ProgramData\Anaconda3\lib\site-packages\geoip.py in _get_actual_db(self)
    348             if self._db is not None:
    349                 return self._db
--> 350             rv = self._load_database()
    351             self._db = rv
    352             return rv

C:\ProgramData\Anaconda3\lib\site-packages\geoip.py in _load_database(self)
    340                 msg += ' It\'s provided by PyPI package "%s"' % self.pypi_name
    341             raise RuntimeError(msg)
--> 342         return mod.loader(self, sys.modules[__name__])
    343 
    344     def _get_actual_db(self):

C:\ProgramData\Anaconda3\lib\site-packages\_geoip_geolite2\__init__.py in loader(database, mod)
      7 def loader(database, mod):
      8     filename = os.path.join(os.path.dirname(__file__), database_name)
----> 9     return mod.open_database(filename)

C:\ProgramData\Anaconda3\lib\site-packages\geoip.py in open_database(filename)
    506     with open(filename, 'rb') as f:
    507         buf = mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ)
--> 508     md = _read_mmdb_metadata(buf)
    509     return MaxMindDatabase(filename, buf, md)

C:\ProgramData\Anaconda3\lib\site-packages\geoip.py in _read_mmdb_metadata(buf)
    380     """Reads metadata from a given memory mapped buffer."""
    381     offset = buf.rfind(MMDB_METADATA_START,
--> 382                        buf.size() - MMDB_METADATA_BLOCK_MAX_SIZE)
    383     if offset < 0:
    384         raise ValueError('Could not find metadata')

TypeError: a bytes-like object is required, not 'str'

**Comment by PetengDedet** [comment]
Hi @ajransaputra 
Thanks for the open issue.
Looks like you're using windows. Since i did not tested it on windows maybe you can explicitly add permission and encoding when reading the file

```python
with open('auth.log', 'r', encoding='UTF-8') as f:
    d = f.readlines() 
```
Then, rerun from the beginning.
Please let me know either it works or not

**Comment by ajransaputra** [comment]
yes use windows and still get same error when add encoding. i will try on my linux

**Comment by ajransaputra** [comment]
i try running with linux get error on
 NameErrorTraceback (most recent call last)
<ipython-input-4-073c1ee1d0d8> in <module>()
      2 attempts = []
      3 
----> 4 for line in d:
      5     obj = get_error_login(line)
      6     if obj:

NameError: name 'd' is not defined

**Comment by ajransaputra** [comment]
thanks working fine in linux, i dont know what exactly error on anaconda windows
